engines:
  pep8:
    enabled: true
  radon:
    enabled: true
    config:
      python_version: 2
  markdownlint:
    enabled: true
ratings:
   paths:
   - "**.py"
   - "**.md"
exclude_paths:
  - "resources/test/"
  - "resources/language/"
  - "resources/media/"
  - "resources/fanart.jpg"
  - "resources/folder.png"
  - "resources/icon.png"
  - "resources/screen_1.png"
  - "resources/screen_2.png"
  - "resources/screen_3.png"
  - "resources/settings.xml"
  - "resources/__init__.py"
  - "resources/lib/__init__.py"
  - "__init__.py"
  - "addon.xml"
  - "LICENSE"
  - "makefile"
  - "requirements.txt"
