sudo: false
language: python

python:
  - "2.7"

script:
  - make all
  - touch ./_build/.nojekyll
  - codeclimate-test-reporter
  - echo $TRAVIS_TAG
  - if [ $TRAVIS_TAG != "" ]; then
    echo 'foo'
    fi
#  - kodi-release -c -o Changelog.md
#  - kodi-release -u

addons:
  apt:
    packages:
      - make

notifications:
  email:
    on_success: change
    on_failure: always

deploy:
  - provider: releases
    github_token: $GITHUB_TOKEN
    tag_name: $CURRENT_VERSION
    name: $CURRENT_VERSION
    body: $LAST_CHANGES
    on:
      tags: true
      branch: master
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: _build
    target_branch: gh-pages
    on:
      tags: true
      branch: master
