sudo: false
language: python

python:
  - "2.7"

addons:
  apt:
    packages:
      - make

jobs:
  include:
    - stage: test
      script: make test
    -
      script: codeclimate-test-reporter
    - stage: lint
      script: make lint
    - stage: docs
      script: make lint
    -
      script: touch ./_build/.nojekyll
    - stage: tag
      script: echo bar
      on:
        branch: master
    - stage: foo
      script: echo foo
      on:
        branch: foobar
    - stage: release
        script: echo "Deploying to GitHub releases ..."
        - deploy:
          provider: releases
          github_token: $GITHUB_TOKEN
          tag_name: $CURRENT_VERSION
          name: $CURRENT_VERSION
          body: $LAST_CHANGES
          on:
            tags: true
            branch: master
    - stage: deploy
        script: echo "Deploying to GitHub pages ..."
        - deploy:
          provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          local_dir: _build
          target_branch: gh-pages
          on:
            tags: true
            branch: master

notifications:
  email:
    on_success: change
    on_failure: always
