sudo: false
language: python

python:
  - "2.7"

script:
  - make all
  - codeclimate-test-reporter
  - export NEXT_VERSION=$(kodi-release -n)
  - export CURRENT_VERSION=$(kodi-release -p)
  - export LATEST_CHANGES=$(kodi-release -l)
  - if [ "$TRAVIS_BRANCH" == "master" ]; then make tag; fi

deploy:
  - provider: releases
    api_key:
      secure: $GITHUB_TOKEN
    tag_name: $(kodi-release -p)
    name: $(kodi-release -p)
    skip_cleanup: true
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: _build
    target_branch: gh-pages
    on:
      branch: master

notifications:
  email:
    on_success: change
    on_failure: always
