language: python

python:
  - "2.7"

before_script:
  - pip install -r requirements.txt
script:
  - make test
after_sucess:
  - codeclimate-test-reporter

addons:
  apt:
    packages:
      - make

notifications:
  email:
    on_success: change
    on_failure: always
