language: python

python:
  - "2.7"

script:
  - python setup.py develop
  - python test.py
after_sucess:
  - codeclimate-test-reporter

addons:
  apt:
    packages:
      - make

notifications:
  email:
    on_success: change
    on_failure: always
