language: python

python:
  - "2.7"

script:
  - python setup.py develop
  - nosetests --version
  - nosetests --help
  - nosetests --nocapture --verbose=DEFAULT --debug=DEBUG --no-path-adjustment --detailed-errors --traverse-namespace --no-byte-compile
after_sucess:
  - codeclimate-test-reporter

addons:
  apt:
    packages:
      - make

notifications:
  email:
    on_success: change
    on_failure: always
