sudo: false
language: python

python:
  - "2.7"

script:
  - make all
  - touch ./_build/.nojekyll
  - codeclimate-test-reporter
  - export NEXT_VERSION=$(kodi-release -n)
  - export CURRENT_VERSION=$(kodi-release -p)
  - export LATEST_CHANGES=$(kodi-release -l)
  - make tag

deploy:
  - provider: releases
    github_token: "$GITHUB_TOKEN"
    tag_name: "$CURRENT_VERSION"
    name: "$CURRENT_VERSION"
    body: "$LAST_CHANGES"
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    local_dir: _build
    target_branch: gh-pages
    on:
      tags: true

notifications:
  email:
    on_success: change
    on_failure: always
